Move MetaWarning classes into new cli module
intel/code-base-investigator pull request #142
Opened 2024-12-17 11:54 UTC by Pennycook

# Related issues

Part of #36, #96.

The CLI is the least well-tested part of Code Base Investigator, because its legacy implementation lived outside of the `codebasin/` package and was therefore difficult to test. Refactoring common CLI functionality into a dedicated module, using functions with well-defined interfaces, will make this functionality more reliable.

# Proposed changes

- Move `Formatter`, `MetaWarning` and `WarningAggregator` into a new `cli` module.
- Add missing docstrings.
- Add unit tests for `Formatter`, `MetaWarning` and `WarningAggregator`.

2025-01-17 16:31 UTC, laserkelvin requested changes

2025-01-17 16:31 UTC, laserkelvin commented on codebasin/cli.py
Not sure if it's just me, but the naming of this module doesn't seem to really fit its contents?

It's called `cli.py` but it contains logging stuff, and if we're moving things around, would it make sense to name it something that maps better? (`log_utils.py`?)

2025-01-17 17:12 UTC, Pennycook commented on codebasin/cli.py
Ah, I can see the confusion.  I'll explain my logic, and you can tell me if it makes sense 😆.

The thinking behind this "cli" module was that it would contain things that were only useful for the user-facing command-line interface, but which might be shared across commands (e.g., the `Formatter` is currently used by both `codebasin` and `cbicov`).

I was basically looking for a way to separate things that we use to build the user-facing CLI from the modules and interfaces that we (eventually) want people to be able to use when importing the `codebasin` package into another script.

Maybe it would be better to have this as something like a `cli` package, containing a `logging.py`?  Or an `_internal` package containing a `logging.py`?  I'm definitely open to suggestions here.

2025-02-27 11:15 UTC, Pennycook commented on codebasin/cli.py
I've renamed this module from "cli" to "_detail.logging" in 9108dcefe6cecde7184cb526e5df1fde4ff9aa76.  Please let me know if it's not what you expected.

2025-02-27 16:17 UTC, laserkelvin approved these changes

2025-02-27 17:11 UTC, merged