Reformat usage string
intel/code-base-investigator pull request #46
Opened 2024-02-06 04:57 UTC by youssefragab99

# Related issues

If applicable: N/A

Closes/Fixes/Addresses #<45>

If not applicable: write "N/A".

# Proposed changes

List out&mdash;with high level descriptions&mdash;what the commits
within this PR do:

- Reformat usage string to contain newline between argument and description
- Consistently formats all usage string descriptions to start with capital letter

2024-02-06 15:33 UTC, Pennycook requested changes
Thanks for taking a look at this. I think there are a few things that you need to address here.

### Sign-off Check

Thank you for reading the contributor guide.  I think you have misunderstood the intent of the sign-off check, though.  Please rewrite history to remove the commit with the certificate of origin.  Your remaining commit should look like this:
```
Add newlines to argparse help strings

Signed-off-by: Youssef Ragab <yragab99@gmail.com>
```

### Formatting

Please install and run the pre-commit hooks:
```
pre-commit install
pre-commit run
```

If you need to run on a specific file:
```
pre-commit run --files codebasin.py
```

There are some formatting changes in your patch that don't look right to me, and this should fix them.

### -h Option

The `-h` option still has the default string, with a lower-case "show":

```
optional arguments:
  -h, --help            show this help message and exit
```

2024-02-06 15:33 UTC, Pennycook commented on codebasin.py
> +    Decrease verbosity level""",
This inserts a newline, but doesn't seem to do so consistently.

The "Increase" and "Decrease" lines have _extra_ indentation compared to other options:
```
  -r DIR, --rootdir DIR
                        Set working root directory (default .)
  -c FILE, --config FILE
                        Configuration file (default: <DIR>/config.yaml)
  -v, --verbose
                            Increase verbosity level
  -q, --quiet
                            Decrease verbosity level
```

2024-02-06 16:05 UTC, laserkelvin requested changes
Echoing @Pennycook comments, particularly regarding the guidelines laid out in the contributor's guide. Additionally, the CI check fails because commits are unsigned, so we are unable to merge it until that is done.

2024-02-06 16:05 UTC, laserkelvin commented on codebasin.py
> +            description="Code Base Investigator v" + str(version),
`black` would modify this block

2024-02-06 16:05 UTC, laserkelvin commented on codebasin.py
> +        help="""
`black` should modify this block

2024-02-06 16:05 UTC, laserkelvin commented on codebasin.py
> +        help="""
`black` should modify this block

2024-02-06 21:06 UTC, youssefragab99 commented
I see the issue, thank you both for the comments @laserkelvin @Pennycook, let me see if I can find a better way of doing this.

2024-03-18 18:51 UTC, Pennycook commented
@youssefragab99 - Are you still working on this?  Our next release is planned for the end of March, and we were hoping to have this fix included there.

2024-03-22 17:20 UTC, Pennycook commented
Closing as stale, and I'll open a new pull request to add the capital letters.  I'll defer the formatting until the next release. 
@youssefragab99, if you're still interested in working on the second part of the fix, please re-open the pull request.

2024-03-22 17:20 UTC, closed without merging